#!/usr/bin/env node
/**
 * Pull the ABIs Foundry just compiled into the SDK as typed TypeScript constants,
 * and copy every deployment address book alongside them.
 *
 * The SDK never reads from contracts/out at runtime and the web app never reads a
 * raw artifact. One generated module, one shape, one place to look.
 *
 *   node scripts/sync-abis.mjs
 */
import { mkdirSync, readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "contracts", "out");
const abiDir = join(root, "packages", "sdk", "src", "generated");

/** Contracts whose ABI the frontend, SDK or MCP server actually calls. */
const CONTRACTS = [
  "DividendRegistry",
  "DripCore",
  "AdvanceVault",
  "StreamEngine",
  "Reinvestor",
  "MockUSDG",
  "MockStockToken",
  "MockSwapAdapter",
];

if (!existsSync(outDir)) {
  console.error("No contracts/out. Run `forge build --root contracts` first.");
  process.exit(1);
}

mkdirSync(abiDir, { recursive: true });

const exports = [];
for (const name of CONTRACTS) {
  const artifactPath = join(outDir, `${name}.sol`, `${name}.json`);
  if (!existsSync(artifactPath)) {
    console.error(`Missing artifact for ${name} at ${artifactPath}`);
    process.exit(1);
  }
  const { abi } = JSON.parse(readFileSync(artifactPath, "utf8"));
  const constName = `${name.charAt(0).toLowerCase()}${name.slice(1)}Abi`;
  writeFileSync(
    join(abiDir, `${constName}.ts`),
    `// Generated by scripts/sync-abis.mjs. Do not edit.\n` +
      `export const ${constName} = ${JSON.stringify(abi, null, 2)} as const;\n`
  );
  exports.push(`export { ${constName} } from "./${constName}";`);
}

// Address books, one per chain id, exactly as the deploy script wrote them.
const deploymentsDir = join(root, "contracts", "deployments");
const books = {};
if (existsSync(deploymentsDir)) {
  for (const file of readdirSync(deploymentsDir)) {
    if (!file.endsWith(".json")) continue;
    const chainId = Number(file.replace(".json", ""));
    books[chainId] = JSON.parse(readFileSync(join(deploymentsDir, file), "utf8"));
  }
}

writeFileSync(
  join(abiDir, "deployments.ts"),
  `// Generated by scripts/sync-abis.mjs. Do not edit.\n` +
    `import type { Deployment } from "../types";\n\n` +
    `export const deployments: Record<number, Deployment> = ${JSON.stringify(books, null, 2)};\n`
);
exports.push(`export { deployments } from "./deployments";`);

writeFileSync(
  join(abiDir, "index.ts"),
  `// Generated by scripts/sync-abis.mjs. Do not edit.\n${exports.join("\n")}\n`
);

const chains = Object.keys(books);
console.log(
  `Synced ${CONTRACTS.length} ABIs and ${chains.length} address book(s)` +
    (chains.length ? ` (chains ${chains.join(", ")})` : "") +
    ` into packages/sdk/src/generated`
);
